# Generated by Django 3.2.7 on 2021-09-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('tool', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='last_tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draw.drawingtools'),
        ),
    ]
